extends: '@ibm-cloud/openapi-ruleset'
rules:
  ibm-no-array-responses: false # TODO: Eventually we want to enable this rule
  ibm-accept-and-return-models: false # THis is disabled as this doesn't seem to work correctly
