// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	"github.com/prometheus/client_golang/prometheus"
)

// DriverChampionship represents a row from 'driver_championship'.
type DriverChampionship struct {
	Id          int     `db:"id,autoinc,pk"`
	SeasonId    int     `db:"season_id"`
	Driver      string  `db:"driver"`
	DriverTag   string  `db:"driver_tag"`
	Nationality string  `db:"nationality"`
	Team        string  `db:"team"`
	Points      float64 `db:"points"`
}

// DriverChampionshipColumns is the sorted column names for the type DriverChampionship
var DriverChampionshipColumns = []string{"Driver", "DriverTag", "Id", "Nationality", "Points", "SeasonId", "Team"}

// Insert inserts the DriverChampionship to the database.
func (m *DriverChampionship) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_DriverChampionship"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO driver_championship (" +
		"`season_id`, `driver`, `driver_tag`, `nationality`, `team`, `points`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		")"

	DBLog(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points)
	res, err := db.Exec(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManyDriverChampionships(db DB, ms ...*DriverChampionship) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_DriverChampionship"))
	defer t.ObserveDuration()

	var sqlstr = "INSERT INTO driver_championship (" +
		"`season_id`,`driver`,`driver_tag`,`nationality`,`team`,`points`" +
		") VALUES"

	var args []interface{}
	for _, m := range ms {
		sqlstr += " (" +
			"?,?,?,?,?,?" +
			"),"
		args = append(args, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *DriverChampionship) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the DriverChampionship in the database.
func (m *DriverChampionship) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_DriverChampionship"))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE driver_championship " +
		"SET `season_id` = ?, `driver` = ?, `driver_tag` = ?, `nationality` = ?, `team` = ?, `points` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points, m.Id)
	res, err := db.Exec(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the DriverChampionship to the database, and tries to update
// on unique constraint violations.
func (m *DriverChampionship) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_DriverChampionship"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO driver_championship (" +
		"`season_id`, `driver`, `driver_tag`, `nationality`, `team`, `points`" +
		") VALUES (" +
		"?, ?, ?, ?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`season_id` = VALUES(`season_id`), `driver` = VALUES(`driver`), `driver_tag` = VALUES(`driver_tag`), `nationality` = VALUES(`nationality`), `team` = VALUES(`team`), `points` = VALUES(`points`)"

	DBLog(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points)
	res, err := db.Exec(sqlstr, m.SeasonId, m.Driver, m.DriverTag, m.Nationality, m.Team, m.Points)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the DriverChampionship to the database.
func (m *DriverChampionship) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the DriverChampionship to the database, but tries to update
// on unique constraint violations.
func (m *DriverChampionship) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the DriverChampionship from the database.
func (m *DriverChampionship) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_DriverChampionship"))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM driver_championship WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// DriverChampionshipById retrieves a row from 'driver_championship' as a DriverChampionship.
//
// Generated from primary key.
func DriverChampionshipById(db DB, id int) (*DriverChampionship, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_DriverChampionship"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `season_id`, `driver`, `driver_tag`, `nationality`, `team`, `points` " +
		"FROM driver_championship " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m DriverChampionship
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

// GetSeason Gets an instance of Season
//
// Generated from constraint driver_championship_season_id_fk
func (m *DriverChampionship) GetSeason(db DB) (*Season, error) {
	return SeasonById(db, m.SeasonId)
}
