// Package models contains the database interaction model code
//
// GENERATED BY GOSCHEMA. DO NOT EDIT.
package models

import (
	usql "github.com/Jacobbrewer1/f1-data/pkg/utils/sql"
	"github.com/prometheus/client_golang/prometheus"
)

// Race represents a row from 'race'.
type Race struct {
	Id        int           `db:"id,autoinc,pk"`
	SeasonId  int           `db:"season_id"`
	GrandPrix string        `db:"grand_prix"`
	Date      usql.NullTime `db:"date"`
}

// RaceColumns is the sorted column names for the type Race
var RaceColumns = []string{"Date", "GrandPrix", "Id", "SeasonId"}

// Insert inserts the Race to the database.
func (m *Race) Insert(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Race"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO race (" +
		"`season_id`, `grand_prix`, `date`" +
		") VALUES (" +
		"?, ?, ?" +
		")"

	DBLog(sqlstr, m.SeasonId, m.GrandPrix, m.Date)
	res, err := db.Exec(sqlstr, m.SeasonId, m.GrandPrix, m.Date)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

func InsertManyRaces(db DB, ms ...*Race) error {
	if len(ms) == 0 {
		return nil
	}

	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_many_Race"))
	defer t.ObserveDuration()

	var sqlstr = "INSERT INTO race (" +
		"`season_id`,`grand_prix`,`date`" +
		") VALUES"

	var args []interface{}
	for _, m := range ms {
		sqlstr += " (" +
			"?,?,?" +
			"),"
		args = append(args, m.SeasonId, m.GrandPrix, m.Date)
	}

	DBLog(sqlstr, args...)
	res, err := db.Exec(sqlstr, args...)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	for i, m := range ms {
		m.Id = int(id + int64(i))
	}

	return nil
}

// IsPrimaryKeySet returns true if all primary key fields are set to none zero values
func (m *Race) IsPrimaryKeySet() bool {
	return IsKeySet(m.Id)
}

// Update updates the Race in the database.
func (m *Race) Update(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("update_Race"))
	defer t.ObserveDuration()

	const sqlstr = "UPDATE race " +
		"SET `season_id` = ?, `grand_prix` = ?, `date` = ? " +
		"WHERE `id` = ?"

	DBLog(sqlstr, m.SeasonId, m.GrandPrix, m.Date, m.Id)
	res, err := db.Exec(sqlstr, m.SeasonId, m.GrandPrix, m.Date, m.Id)
	if err != nil {
		return err
	}

	// Requires clientFoundRows=true
	if i, err := res.RowsAffected(); err != nil {
		return err
	} else if i <= 0 {
		return ErrNoAffectedRows
	}

	return nil
}

// InsertWithUpdate inserts the Race to the database, and tries to update
// on unique constraint violations.
func (m *Race) InsertWithUpdate(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_update_Race"))
	defer t.ObserveDuration()

	const sqlstr = "INSERT INTO race (" +
		"`season_id`, `grand_prix`, `date`" +
		") VALUES (" +
		"?, ?, ?" +
		") ON DUPLICATE KEY UPDATE " +
		"`season_id` = VALUES(`season_id`), `grand_prix` = VALUES(`grand_prix`), `date` = VALUES(`date`)"

	DBLog(sqlstr, m.SeasonId, m.GrandPrix, m.Date)
	res, err := db.Exec(sqlstr, m.SeasonId, m.GrandPrix, m.Date)
	if err != nil {
		return err
	}

	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	m.Id = int(id)
	return nil
}

// Save saves the Race to the database.
func (m *Race) Save(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.Insert(db)
}

// SaveOrUpdate saves the Race to the database, but tries to update
// on unique constraint violations.
func (m *Race) SaveOrUpdate(db DB) error {
	if m.IsPrimaryKeySet() {
		return m.Update(db)
	}
	return m.InsertWithUpdate(db)
}

// Delete deletes the Race from the database.
func (m *Race) Delete(db DB) error {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("delete_Race"))
	defer t.ObserveDuration()

	const sqlstr = "DELETE FROM race WHERE `id` = ?"

	DBLog(sqlstr, m.Id)
	_, err := db.Exec(sqlstr, m.Id)

	return err
}

// RaceById retrieves a row from 'race' as a Race.
//
// Generated from primary key.
func RaceById(db DB, id int) (*Race, error) {
	t := prometheus.NewTimer(DatabaseLatency.WithLabelValues("insert_Race"))
	defer t.ObserveDuration()

	const sqlstr = "SELECT `id`, `season_id`, `grand_prix`, `date` " +
		"FROM race " +
		"WHERE `id` = ?"

	DBLog(sqlstr, id)
	var m Race
	if err := db.Get(&m, sqlstr, id); err != nil {
		return nil, err
	}

	return &m, nil
}

// GetSeason Gets an instance of Season
//
// Generated from constraint race_season_id_fk
func (m *Race) GetSeason(db DB) (*Season, error) {
	return SeasonById(db, m.SeasonId)
}
