// Package data provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package data

// Season defines the model for season.
type Season struct {
	Id   *int64 `json:"id,omitempty"`
	Year *int64 `json:"year,omitempty"`
}
