// Package data provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package data

import (
	externalRef0 "github.com/jacobbrewer1/f1-data/pkg/codegen/apis/common"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ConstructorChampionship defines the model for constructor_championship.
type ConstructorChampionship struct {
	Id       *int64   `json:"id,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Points   *float32 `json:"points,omitempty"`
	Position *int64   `json:"position,omitempty"`
}

// ConstructorChampionshipResponse defines the model for constructor_championship_response.
type ConstructorChampionshipResponse struct {
	Constructors []ConstructorChampionship `json:"constructors"`
	Total        int64                     `json:"total"`
}

// Driver defines the model for driver.
type Driver struct {
	Name        *string `json:"name,omitempty"`
	Nationality *string `json:"nationality,omitempty"`
	Tag         *string `json:"tag,omitempty"`
}

// DriverChampionship defines the model for driver_championship.
type DriverChampionship struct {
	Id          *int64   `json:"id,omitempty"`
	Name        *string  `json:"name,omitempty"`
	Nationality *string  `json:"nationality,omitempty"`
	Points      *float32 `json:"points,omitempty"`
	Position    *int64   `json:"position,omitempty"`
	Tag         *string  `json:"tag,omitempty"`
	Team        *string  `json:"team,omitempty"`
}

// DriverChampionshipResponse defines the model for driver_championship_response.
type DriverChampionshipResponse struct {
	Drivers []DriverChampionship `json:"drivers"`
	Total   int64                `json:"total"`
}

// DriverResponse defines the model for driver_response.
type DriverResponse struct {
	Drivers []Driver `json:"drivers"`
	Total   int64    `json:"total"`
}

// Race defines the model for race.
type Race struct {
	Date *openapi_types.Date `json:"date,omitempty"`
	Id   *int64              `json:"id,omitempty"`
	Name *string             `json:"name,omitempty"`
}

// RaceResponse defines the model for race_response.
type RaceResponse struct {
	Races []Race `json:"races"`
	Total int64  `json:"total"`
}

// RaceResult defines the model for race_result.
type RaceResult struct {
	DriverName    *string  `json:"driver_name,omitempty"`
	DriverNumber  *int64   `json:"driver_number,omitempty"`
	DriverTag     *string  `json:"driver_tag,omitempty"`
	Id            *int64   `json:"id,omitempty"`
	LapsCompleted *int64   `json:"laps_completed,omitempty"`
	Points        *float32 `json:"points,omitempty"`
	Position      *string  `json:"position,omitempty"`
	TeamName      *string  `json:"team_name,omitempty"`
	TimeOrRetired *string  `json:"time_or_retired,omitempty"`
}

// RaceResultResponse defines the model for race_result_response.
type RaceResultResponse struct {
	Results []RaceResult `json:"results"`
	Total   int64        `json:"total"`
}

// Season defines the model for season.
type Season struct {
	Id   *int64 `json:"id,omitempty"`
	Year *int64 `json:"year,omitempty"`
}

// SeasonResponse defines the model for season_response.
type SeasonResponse struct {
	Seasons []Season `json:"seasons"`
	Total   int64    `json:"total"`
}

// PathRaceId defines the model for path_race_id.
type PathRaceId = int64

// PathYear defines the model for path_year.
type PathYear = int64

// QueryName defines the model for query_name.
type QueryName = string

// QueryNationality defines the model for query_nationality.
type QueryNationality = string

// QueryTag defines the model for query_tag.
type QueryTag = string

// QueryTeam defines the model for query_team.
type QueryTeam = string

// QueryYear defines the model for query_year.
type QueryYear = int64

// QueryYearMax defines the model for query_year_max.
type QueryYearMax = int64

// QueryYearMin defines the model for query_year_min.
type QueryYearMin = int64

// GetConstructorsChampionshipParams defines parameters for GetConstructorsChampionship.
type GetConstructorsChampionshipParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetConstructorsChampionshipParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Name The name to filter by
	Name *QueryName `form:"name,omitempty" json:"name,omitempty"`
}

// GetConstructorsChampionshipParamsSortDir defines parameters for GetConstructorsChampionship.
type GetConstructorsChampionshipParamsSortDir string

// GetDriversChampionshipParams defines parameters for GetDriversChampionship.
type GetDriversChampionshipParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetDriversChampionshipParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Name The name to filter by
	Name *QueryName `form:"name,omitempty" json:"name,omitempty"`

	// Tag The tag to filter by
	Tag *QueryTag `form:"tag,omitempty" json:"tag,omitempty"`

	// Team The team to filter by
	Team *QueryTeam `form:"team,omitempty" json:"team,omitempty"`
}

// GetDriversChampionshipParamsSortDir defines parameters for GetDriversChampionship.
type GetDriversChampionshipParamsSortDir string

// GetDriversParams defines parameters for GetDrivers.
type GetDriversParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetDriversParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Name The name to filter by
	Name *QueryName `form:"name,omitempty" json:"name,omitempty"`

	// Tag The tag to filter by
	Tag *QueryTag `form:"tag,omitempty" json:"tag,omitempty"`

	// Team The team to filter by
	Team *QueryTeam `form:"team,omitempty" json:"team,omitempty"`

	// Nationality The nationality to filter by
	Nationality *QueryNationality `form:"nationality,omitempty" json:"nationality,omitempty"`
}

// GetDriversParamsSortDir defines parameters for GetDrivers.
type GetDriversParamsSortDir string

// GetRaceResultsParams defines parameters for GetRaceResults.
type GetRaceResultsParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetRaceResultsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// GetRaceResultsParamsSortDir defines parameters for GetRaceResults.
type GetRaceResultsParamsSortDir string

// GetSeasonsParams defines parameters for GetSeasons.
type GetSeasonsParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetSeasonsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// Year The year of the season
	Year *QueryYear `form:"year,omitempty" json:"year,omitempty"`

	// YearMin The minimum year of the season
	YearMin *QueryYearMin `form:"year_min,omitempty" json:"year_min,omitempty"`

	// YearMax The maximum year of the season
	YearMax *QueryYearMax `form:"year_max,omitempty" json:"year_max,omitempty"`
}

// GetSeasonsParamsSortDir defines parameters for GetSeasons.
type GetSeasonsParamsSortDir string

// GetSeasonRacesParams defines parameters for GetSeasonRaces.
type GetSeasonRacesParams struct {
	// Limit Report type
	Limit *externalRef0.LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// LastVal Pagination details, last value of the sort column on the previous page.
	LastVal *externalRef0.LastValue `form:"last_val,omitempty" json:"last_val,omitempty"`

	// LastId Pagination details, last value of the id column on the previous page.
	LastId *externalRef0.LastId `form:"last_id,omitempty" json:"last_id,omitempty"`

	// SortBy Pagination details, sort column, if empty uses the id column.
	SortBy *externalRef0.SortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Pagination details, sorting order.
	SortDir *GetSeasonRacesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// GetSeasonRacesParamsSortDir defines parameters for GetSeasonRaces.
type GetSeasonRacesParamsSortDir string
